INSERT INTO `DEPARTMENT`(`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES ('1', 'IT');
INSERT INTO `DEPARTMENT`(`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES ('2', 'HR');
INSERT INTO `DEPARTMENT`(`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES ('3','MG');
INSERT INTO `EMPLOYEE` (`EMPLOYEE_ID`, `FIRST_NAME`, `LAST_NAME`, `PESEL`, `SALARY`, `DEPARTMENT_ID`) VALUES ('1', 'Szymon', 'Pawełek', '73022400892', '3000', '2');
INSERT INTO `EMPLOYEE` (`EMPLOYEE_ID`, `FIRST_NAME`, `LAST_NAME`, `PESEL`, `SALARY`, `DEPARTMENT_ID`) VALUES ('2', 'Julia', 'Guzik', '83122467842', '4000', '1');
INSERT INTO `EMPLOYEE` (`EMPLOYEE_ID`, `FIRST_NAME`, `LAST_NAME`, `PESEL`, `SALARY`, `DEPARTMENT_ID`) VALUES ('3', 'Jan', 'Dul', '53123427814', '7000', '1');