INSERT INTO `DEPARTMENT`(`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES ('1', 'IT');
INSERT INTO `DEPARTMENT`(`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES ('2', 'HR');
INSERT INTO `DEPARTMENT`(`DEPARTMENT_ID`,`DEPARTMENT_NAME`) VALUES ('3','MG');
